# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b39404da62770378836bcd01d04dbe5a6f0f41d37e36ba394bbfbf099f428599af0a2430876b2e3037c5af465b017227b604cf24e34806e888d86b180efd55

test:
  secret_key_base: 1341bf3c0a76cc0f2004df24b781505938eb5d76890aa428b5fa0bef3e3f1b7b1c9fa8ef90fdf5e38fc58d20d1b9612551ca45456eb95ddf6654538177c10414

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
